Bootstrap: localimage
From: ubuntu_{{ UBUNTU_VERSION }}.sif
%labels
MAINTAINER  Edoardo Apra <edoardo.apra@pnnl.gov>

%arguments
   UBUNTU_VERSION=jammy

%files
#exachem_ecpint.patch /opt/

%setup
    #!/bin/bash
    echo "$(readlink /proc/$$/exe) is the shell in use"
    env|egrep SHELL
    ls -la  ${GITHUB_WORKSPACE}
    export CACHEDIR=${GITHUB_WORKSPACE}/../../../cache
#    echo '@@@ ls -l $SINGULARITY_ROOTFS'
#    ls -l ${SINGULARITY_ROOTFS}
    rm -f ${SINGULARITY_ROOTFS}/*.txt || true
    bash -c "if [[ -z '${GPU}' ]]; then echo 'GPU=nvidia ' >> ${SINGULARITY_ROOTFS}/gpu.txt ; else echo 'GPU is ${GPU}'; echo 'GPU=${GPU} ' >> ${SINGULARITY_ROOTFS}/gpu.txt ; fi"
    bash -c "echo 'ELPA is ${ELPA}'; echo 'ELPA=${ELPA} ' >> ${SINGULARITY_ROOTFS}/elpa.txt "
    cat ${SINGULARITY_ROOTFS}/elpa.txt
    bash -c "if [[ -z '${MPI_IMPL}' ]]; then echo 'MPI_IMPL=mpich ' >> ${SINGULARITY_ROOTFS}/mpi_impl.txt ; else echo 'MPI_IMPL is ${MPI_IMPL}'; echo 'MPI_IMPL=${MPI_IMPL} ' >> ${SINGULARITY_ROOTFS}/mpi_impl.txt ; fi"
    bash -c "if [[ -z '${OMPI}' ]]; then echo 'OMPI=4.1.6 ' >> ${SINGULARITY_ROOTFS}/OMPI.txt ; else echo 'OMPI is ${OMPI}'; echo 'OMPI=${OMPI} ' >> ${SINGULARITY_ROOTFS}/ompi.txt ; fi"
    bash -c "if [[ '${OFI}' != "N" ]]; then echo 'OFI is ${OFI}'; echo 'OFI=${OFI} ' >> ${SINGULARITY_ROOTFS}/ofi.txt ; fi"
    bash -c "if [[ -z '${GA_RUNTIME}' ]]; then echo 'GA_RUNTIME=MPI_2SIDED ' >> ${SINGULARITY_ROOTFS}/ga_runtime.txt ; else echo 'GA_RUNTIME is ${GA_RUNTIME}'; echo 'GA_RUNTIME=${GA_RUNTIME} ' >> ${SINGULARITY_ROOTFS}/ga_runtime.txt ; fi"
    bash -c "if [[ -z '${MPICH}' ]]; then echo 'MPICH=3.4.2 ' >> ${SINGULARITY_ROOTFS}/mpich.txt ; else echo 'MPICH is ${MPICH}'; echo 'MPICH=${MPICH} ' >> ${SINGULARITY_ROOTFS}/mpich.txt ; fi"
    bash -c "if [[ -z '${MPICH_DEVICE}' ]]; then echo 'MPICH_DEVICE=ch4:ofi ' >> ${SINGULARITY_ROOTFS}/mpich_device.txt ; else echo 'MPICH_DEVICE is ${MPICH_DEVICE}'; echo 'MPICH_DEVICE=${MPICH_DEVICE} ' >> ${SINGULARITY_ROOTFS}/mpich_device.txt ; fi"
    bash -c "if [[ -z '${TAMM_BRANCH}' ]]; then echo 'TAMM_BRANCH=main ' >> ${SINGULARITY_ROOTFS}/branch.txt ; else echo 'TAMM_BRANCH is ${TAMM_BRANCH}'; echo 'TAMM_BRANCH=${TAMM_BRANCH} ' >> ${SINGULARITY_ROOTFS}/tamm_branch.txt ; fi"
    bash -c "if [[ -z '${EXACHEM_BRANCH}' ]]; then echo 'EXACHEM_BRANCH=main ' >> ${SINGULARITY_ROOTFS}/branch.txt ; else echo 'EXACHEM_BRANCH is ${EXACHEM_BRANCH}'; echo 'EXACHEM_BRANCH=${EXACHEM_BRANCH} ' >> ${SINGULARITY_ROOTFS}/exachem_branch.txt ; fi"
#    bash -c "if [[ -z '${MYUSERNAME}' ]]; then echo 'MYUSERNAME=edoapra ' >> ${SINGULARITY_ROOTFS}/myusername.txt ; else echo 'MYUSERNAME is ${MYUSERNAME}'; echo 'MYUSERNAME=${MYUSERNAME} ' >> ${SINGULARITY_ROOTFS}/myusername.txt ; fi"
    ls -lrt ${CACHEDIR} || true
    ls -la  ${CACHEDIR}/ || true
    ls -la  ${CACHEDIR}/ompi || true
    ls -la  ${CACHEDIR}/ompi/lib || true
    ls -la  ${CACHEDIR}/libint.tar.bz2 || true
    bash -c "if [[  -f ${CACHEDIR}/ompi/lib/libmpi.so ]]; then mkdir -p ${SINGULARITY_ROOTFS}/opt ;rsync -a ${CACHEDIR}/ompi ${SINGULARITY_ROOTFS}/opt/. ; echo ompi/ucx cache fetched ;fi"
    bash -c "if [[  -f ${CACHEDIR}/libint.tar.bz2 ]]; then cd ${SINGULARITY_ROOTFS}/ ; tar xvjf ${CACHEDIR}/libint.tar.bz2; echo libint cache fetched ;fi"
    ls -lrta ${SINGULARITY_ROOTFS}/opt  ||true

%post 
#!/bin	/bash

echo "$(readlink /proc/$$/exe) is the shell in use"
#
export `cat ./gpu.txt`
export `cat ./elpa.txt`
bash -o  pipefail -c "if [[ $(echo $GPU | cut -c 1-3)  == 'amd' ]]; then echo gpus is amd;
echo 'ROCM_VERSION='`echo $GPU | cut -c 16-` > rocm_version.txt ;
echo 'GPU_ARCH='`echo $GPU | cut -c 5-10` > gpu_arch.txt ;
echo 'GPU=amd ' >  gpu.txt  ; fi"
bash -o  pipefail -c "if [[ $(echo $GPU | cut -c 1-6)  == 'nvidia' ]]; then echo gpus is nvidia;
echo 'GPU_ARCH='`echo $GPU | cut -c 8-9` > gpu_arch.txt ;
echo 'GPU=nvidia ' >  gpu.txt  ; fi"
export `cat ./gpu.txt`
export `cat ./rocm_version.txt`
export `cat ./gpu_arch.txt`
if [ ${GPU} = "nvidia" ]; then export CUDA_VERSION_MAJOR=12 ; export CUDA_VERSION_MINOR=4;fi
export ROCM_PATH=/opt/rocm-${ROCM_VERSION}
if [ ${#ROCM_VERSION} = 3 ]; then export ROCM_PATH="$ROCM_PATH".0; fi
echo ROCM_PATH is $ROCM_PATH
echo GPU is $GPU
export GCC_VERSION=12
export EXACHEM_BRANCH=main
export TAMM_BRANCH=main


export PATH=$MPI_DIR/bin:/usr/local/cuda-"$CUDA_VERSION_MAJOR"."$CUDA_VERSION_MINOR"/bin::/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:"$ROCM_PATH"/bin
export LD_LIBRARY_PATH=/usr/local/cuda-"$CUDA_VERSION_MAJOR"."$CUDA_VERSION_MINOR"/lib64:/usr/local/lib:$MPI_DIR/lib:"$ROCM_PATH"/lib
export SINGULARITY_PATH=$PATH
export SINGULARITY_LD_LIBRARY_PATH=$LD_LIBRARY_PATH
export `cat ./ga_runtime.txt`
export `cat ./exachem_branch.txt`
export `cat ./tamm_branch.txt`
 if [ ! -f ./mpi_impl.txt ]; then
     echo MPI_IMPL not defined
     exit 1
 else
     export `cat ./mpi_impl.txt`
     echo MPI_IMPL is $MPI_IMPL
 fi
 if [ $MPI_IMPL = "ompi" ]; then
     if [ ! -f ./ompi.txt ]; then
	 echo OMPI not defined
	 exit 1
     else
	 export `cat ./ompi.txt`
	 echo OMPI is $OMPI
     fi
     export OMPI_DIR=/opt/mpi
     export MPI_DIR=/opt/mpi
     export ompi_prefix=openmpi-$OMPI
     echo ompi_prefix is $ompi_prefix 
     export ompi_major=$(echo $OMPI | cut -d . -f1) 
     echo ompi_major is $ompi_major 
     export ompi_minor=$(echo $OMPI | cut -d . -f2) 
     echo ompi_minor is $ompi_minor 
     echo ompi_major is $ompi_major 
     if [ $ompi_major = '5' ]; then
	 export ompi_options=' --enable-mca-no-build=coll-han '
     else
	 export ompi_options=' --with-pmi --with-pmi-libdir=/usr/lib/x86_64-linux-gnu --without-verbs '
     fi 
     echo ompi_options $ompi_options 
     mpich_major=-1
     mpich_minor=-1
 fi
 if [ $MPI_IMPL = "mpich" ]; then
     if [ ! -f ./mpich.txt ]; then
	 ls -lrt *txt
	 echo MPICH not defined
	 exit 1
     else
	 export `cat ./mpich.txt`
	 echo MPICH is $MPICH
     fi
     export MPICH_DIR=/opt/mpi
     export MPI_DIR=/opt/mpi

     if [ $MPICH = aurora ]; then
	 export MPICH_VERSION=$MPICH_AURORA
     else
	 export MPICH_VERSION=$MPICH
     fi
     if [ ! -f ./mpich_device.txt ]; then
	 echo MPICH_DEVICE not defined
	 exit 1
     else
	 export `cat ./mpich_device.txt`
	 echo MPICH_DEVICE is $MPICH_DEVICE
     fi
     export mpich_prefix=mpich-$MPICH_VERSION
     echo mpich_prefix is $mpich_prefix 
     export mpich_major=$(echo $MPICH_VERSION | cut -d . -f1) 
     echo mpich_major is $mpich_major 
     export mpich_minor=$(echo $MPICH_VERSION | cut -d . -f2) 
     echo mpich_minor is $mpich_minor 
     echo mpich_major is $mpich_major 
     if [ $mpich_major = '4' ]; then
	 export mpich_options=' '
     else
	 export mpich_options=' '
     fi 
     if [ $MPICH = aurora ]; then
	 export mpich_options=$mpich_options' --disable-maintainer-mode --with-pm=no --enable-romio --with-slurm=no --with-pmi=pmix --with-pmix=/opt/mpi '
     fi
     echo mpich_options are $mpich_options
     ompi_major=-1
     ompi_minor=-1
 fi
 if [  -f ./ucx.txt ]; then
     echo cat ucx `cat ./ucx.txt`
     export `cat ./ucx.txt`
     echo UCX is $UCX
     if [ $UCX != "N" ]; then
	 export UCXVTAG=v$UCX 
	 echo standard UCXVTAG is $UCXVTAG 
	 echo UCX is $UCX UCXVTAG is $UCXVTAG
	 if [ $MPI_IMPL = "ompi" ]; then
             export ucx_or_ofi=" --enable-mca-no-build=btl-uct "
	 fi
         export ucx_or_ofi="$ucx_or_ofi --with-ucx="${MPI_DIR}
     fi
 fi
 if [  -f ./ofi.txt ]; then
      export `cat ./ofi.txt`
      echo OFI is $OFI
      if [ $OFI != "N" ]; then
	  if [ $MPI_IMPL = "mpich" ]; then
	      if [ $OFI != "builtin" ]; then
		  export ucx_or_ofi="--with-libfabric="${MPI_DIR}
	      fi
	  else
	      export ucx_or_ofi="--with-ofi="${MPI_DIR}
	  fi
      fi
 fi
 if [ $UCX = "N" ] &&  [ $OFI = "N" ]; then
     echo neither UCX nor OFI defined
     echo exiting
     exit 1
 fi
 if [ $UCX != "N" ] &&  [ $OFI != "N" ]; then
     echo both UCX and OFI are set
     echo exiting
     exit 1
 fi
 if [  -f ./pmix.txt ]; then
      export `cat ./pmix.txt`
      echo PMIX is $PMIX
      if [ $PMIX != "N" ]; then
	  if [ $MPI_IMPL = "mpich" ]; then
	      export pmix_options="--with-pmi=pmix"
	  fi
	  export pmix_options="${pmix_options} --with-pmix=${MPI_DIR}"
      fi
 fi
echo ucx_or_ofi is $ucx_or_ofi
echo GPU is $GPU
echo ROCM_PATH is ${ROCM_PATH}
echo GA_RUNTIME is $GA_RUNTIME
echo MPI_IMPL is $MPI_IMPL
echo EXACHEM_BRANCH is $EXACHEM_BRANCH
echo TAMM_BRANCH is $TAMM_BRANCH
export MYROOT=/
if [ "$GPU" = "amd" ]
then
    export FC=amdflang ; export CC=amdclang; export CXX=amdclang++
else
       export FC=gfortran ; export CC=gcc; export CXX=g++
fi
echo 'FC is' "$FC"  
echo ' CC is ' "$CC" 
echo ' CXX is ' "$CXX" 
cd / 
pwd 
apt-get -y update 
apt-get -y install -y tzdata git moreutils  wget rsync  sudo ca-certificates
wget https://github.com/moparisthebest/static-curl/releases/download/v8.1.2/curl-amd64 -O /usr/bin/curl
chmod +x /usr/bin/curl
echo ca_certificate=/etc/ssl/certs/ca-certificates.crt >  ~/.wgetrc
echo        "cacert=/etc/ssl/certs/ca-certificates.crt" >> ~/.curlrc
export CMAKE_VER=3.29.5
curl -LJO https://github.com/Kitware/CMake/releases/download/v"$CMAKE_VER"/cmake-"$CMAKE_VER"-linux-x86_64.tar.gz && tar xzf cmake-"$CMAKE_VER"-linux-x86_64.tar.gz
export PATH=/cmake-"$CMAKE_VER"-linux-x86_64/bin:$PATH
apt-get -y install -y  gfortran
pwd
echo '@@ ls -lart '
ls -lart 
echo '@@ ls on /opt'
ls -lart /opt
echo " =========="
pwd
echo pwd $(pwd)
apt-get -y install -y coreutils  tar libnl-3-200 libnl-route-3-200 libgomp1 libnuma1 \
 g++ gfortran   make ssh patch   unzip perl-base file \
 python3 python3-dev cmake  unzip zip perl automake libtool autoconf flex  \
 libnuma-dev libslurm-dev libpmi2-0-dev  libnl-3-dev libnl-route-3-dev udev \
 librdmacm-dev librdmacm1 rdma-core libibverbs-dev  ibverbs-providers \
 libhwloc-dev  librte-common-mlx5-2* librte-net-mlx5-2* librte-compress-mlx5-2* librte-crypto-mlx5-2* librte-regex-mlx5-2* librte-vdpa-mlx5-2* \
 pkg-config gawk  software-properties-common linux-headers-generic lsb-release 
if [ $ompi_major = '5' ]
then
    apt-get -y install -y libpmix-bin libpmix-dev libpmix2
else
    apt-get -y install -y libpmi2-0-dev libpmi0-dev
fi 
apt-get install -q=2 -y  gcc-"$GCC_VERSION"  g++-"$GCC_VERSION" gfortran-"$GCC_VERSION" libgfortran-"$GCC_VERSION"-dev  make ssh patch curl rsync wget git file  bzip2 tar gnupg2 cmake 
update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-"$GCC_VERSION" 100
update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-"$GCC_VERSION" 100
update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-"$GCC_VERSION" 100
apt-get install  -q=2 -y  autoconf automake libtool git
 export UBUNTU_CODE=$(lsb_release -c |cut -d : -f 2 | sed 's/\t//') 
 echo UBUNTU_CODE is $UBUNTU_CODE 
 export UBUNTU_RELEASE=$(lsb_release -r |cut -d : -f 2 | sed 's/\t//') 
 echo UBUNTU_RELEASE is $UBUNTU_RELEASE 
if [ $GPU == "nvidia" ]
then 	    
    curl -LJO https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-archive-keyring.gpg 
    cp cuda-archive-keyring.gpg /usr/share/keyrings/cuda-archive-keyring.gpg 
    echo 'deb [signed-by=/usr/share/keyrings/cuda-archive-keyring.gpg] https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/ /' |  tee /etc/apt/sources.list.d/cuda-ubuntu2204-x86_64.list
    curl -LJO https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-ubuntu2204.pin
    mv cuda-*.pin /etc/apt/preferences.d/cuda-repository-pin-600
    apt-get  update
    apt-get  -y install cuda-nvcc-${CUDA_VERSION_MAJOR}-${CUDA_VERSION_MINOR} cuda-cudart-dev-${CUDA_VERSION_MAJOR}-${CUDA_VERSION_MINOR} cuda-libraries-${CUDA_VERSION_MAJOR}-${CUDA_VERSION_MINOR} cuda-libraries-dev-${CUDA_VERSION_MAJOR}-${CUDA_VERSION_MINOR} libcublas-dev-${CUDA_VERSION_MAJOR}-${CUDA_VERSION_MINOR} cuda-libraries-${CUDA_VERSION_MAJOR}-${CUDA_VERSION_MINOR} cuda-nvml-dev-${CUDA_VERSION_MAJOR}-${CUDA_VERSION_MINOR}
fi

if [ $GPU = "amd" ]
then
    mkdir --parents --mode=0755 /etc/apt/keyrings 
    wget --quiet https://repo.radeon.com/rocm/rocm.gpg.key -O - |  gpg --dearmor | tee /etc/apt/keyrings/rocm.gpg > /dev/null
    echo ROCM_VERSION is $ROCM_VERSION
    echo UBUNTU_CODE is $UBUNTU_CODE
    echo 'deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/rocm/apt/'${ROCM_VERSION} ${UBUNTU_CODE} 'main' | tee --append /etc/apt/sources.list.d/rocm.list
    echo cat /etc/apt/sources.list.d/rocm.list
    cat /etc/apt/sources.list.d/rocm.list
    echo  'Package: *\nPin: release o=repo.radeon.com\nPin-Priority: 600' >e /etc/apt/preferences.d/rocm-pin-600 
    apt-get  update -y &&  apt-get -y install hip-dev hipcc hip-runtime-amd rocm-llvm rocm-device-libs rocblas-dev openmp-extras rocm-smi-lib rocminfo  hipcc hipblas-dev 
    ls -lrt /opt
    ls -lrt  /opt/rocm* || true
    echo "$GPU_ARCH" >> $ROCM_PATH/bin/target.lst
    echo 'rrrr' $(cat  $ROCM_PATH/bin/target.lst)
    echo '$$$$$$$$$$$$$$$$$$$$'
    echo 'rocminfo' $(rocm_agent_enumerator)
    echo '$$$$$$$$$$$$$$$$$$$$'
    echo 'hipcc --version' $(hipcc --version)
    echo '$$$$$$$$$$$$$$$$$$$$'
    echo 'hipconfig' $(hipconfig)
    echo '$$$$$$$$$$$$$$$$$$$$'
    echo ' ls -l  ROCM_PATH/lib' $(ls -l $ROCM_PATH/lib)  
    echo '$$$$$$$$$$$$$$$$$$$$'
    echo ' ls -l  ROCM_PATH/lib/libamdhip64.so*' $(ls -l $ROCM_PATH/lib/libamdhip64.so*)  
    echo '$$$$$$$$$$$$$$$$$$$$' 
    wget --quiet https://download.amd.com/developer/eula/blis/blis-4-1/aocl-blis-linux-aocc-4.1.0.tar.gz -O - | tar xzf - -C /opt
fi 
echo 'FC -v ' `$FC -v` 
echo 'CC -v ' `$CC -v` 
echo 'CXX -v ' `$CXX -v` || { echo "CXX not installed"; exit  1; }
apt-get clean 
export ORGPWD=$(pwd)
echo ORGPWD is $ORGPWD
if [ $UCX != "N" ]; then
    echo check ucx install 
    echo 'ls -l /opt/mpi/lib/libuct.so' $(ls -l /opt/mpi/lib/libuct.so) || true 
    if [ ! -f /opt/mpi/lib/libuct.so ]; then  
	$FC -v 
	wget --progress=dot:giga  https://github.com/openucx/ucx/releases/download/$UCXVTAG/ucx-$UCX.tar.gz -O - | tar xzf - 
	cd ucx-$UCX 
	wget https://raw.githubusercontent.com/edoapra/nwchem-singularity/master/nwchem-dev.ompi41x.ifx/ucx_malloc.patch 
	wget https://raw.githubusercontent.com/edoapra/nwchem-singularity/master/nwchem-dev.ompi5x/ucx1181_malloc.patch 
	if [ $UCX = 1.14.1 ] || [ $UCX = 1.15.0 ]; then
	    patch -p0 < ./ucx_malloc.patch
	else
	    patch -p0 < ./ucx1181_malloc.patch
	fi 
	mkdir build && cd build 
	../configure --prefix=$MPI_DIR --disable-logging --disable-debug --disable-assertions --disable-params-check || { echo "UCX config Failure"; exit 1; }
	make -j4 || { echo "UCX Compilation Failure"; exit 1; }
	make install || { echo "UCX Installation Failure"; exit 1; }
	if [ ! -f $MPI_DIR/bin/ucx_info ]; then echo ucx_info\ not\ found ; exit 1 ; fi 
	cd $ORGPWD
    else
	echo "using UCX cached installtation"
    fi
    echo ' check ucx' 
    if [ ! -f $MPI_DIR/bin/ucx_info ]; then echo ucx_info\ not\ found ; exit 1 ; fi 
    echo ' /opt/mpi/bin/ucx_info -v ' `/opt/mpi/bin/ucx_info -v|| true` 
    echo ' ucx Transports' `/opt/mpi/bin/ucx_info  -d |grep Transport |cut -c 19- || true` 
fi
if [ $OFI != "N" ]; then
#    #install cxi
#    echo 'ls -l /opt/mpi/shs-cassini-headers/cray-cassini-headers-public.spec' $(ls -l /opt/mpi/shs-cassini-headers/cray-cassini-headers-public.spec) || true 
#    if [ ! -f /opt/mpi/shs-cassini-headers/cray-cassini-headers-public.spec ]; then  
#	cd / ; ls -lrta  
#	mkdir -p $MPI_DIR  
#	cd $MPI_DIR
#	export SHSTAG=release/shs-12.0.2
#	wget --progress=dot:giga https://github.com/HewlettPackard/shs-cassini-headers/archive/refs/heads/main.tar.gz -O - | tar xzf -
#	mv shs-cassini-headers* shs-cassini-headers
##	git clone --branch $SHSTAG https://github.com/HewlettPackard/shs-cxi-driver
#	wget https://github.com/HewlettPackard/shs-cxi-driver/archive/refs/tags/${SHSTAG}.tar.gz -O - |tar xzf -
#	mv shs-cxi-driver* shs-cxi-driver
#	cd $ORGPWD
#	wget --progress=dot:giga https://github.com/HewlettPackard/shs-libcxi/archive/refs/tags/${SHSTAG}.tar.gz -O - | tar xzf -
#	mv shs-libcxi-* shs-libcxi
#	cd shs-libcxi 
#	sh autogen.sh 
#	./configure --prefix=$MPI_DIR 
#	make CFLAGS=-I$MPI_DIR/shs-cassini-headers/include/\ -I$MPI_DIR/shs-cxi-driver/include/ pkg_CFLAGS=-Wall -i 
#	make CFLAGS=-I$MPI_DIR/shs-cassini-headers/include/\ -I$MPI_DIR/shs-cxi-driver/include/ install-dist_cxi_yamlDATA install-man install-pkgconfigDATA install-pkgincludeHEADERS  install-exec   
#	export libfabric_options=--enable-cxi=$MPI_DIR\ --with-cassini-headers=$MPI_DIR/shs-cassini-headers\ --with-cxi-uapi-headers=$MPI_DIR/shs-cxi-driver
#	echo 'libfabric_options are' $libfabric_options
#	rm -rf shs-*
#    fi
    cd  $ORGPWD
    #install OFI
    echo 'ls -l /opt/mpi/lib/libfabrics.so' $(ls -l /opt/mpi/lib/libfabrics.so) || true 
    if [ ! -f /opt/mpi/lib/libfabrics.so ]; then  
	if [ ${OFI} = builtin ]; then
	    echo 'using builtin OFI - nothing to download'
	else
	    if [ ${OFI} = git ]; then
		export COMMIT=c3420a7402a10f5fe3f475ac5eb39b3f2837f8d1
		wget  --progress=dot:giga https://github.com/ofiwg/libfabric/archive/$COMMIT.tar.gz -O - | tar --no-same-owner xzf -
		ls -lrt 
		mv libfabric-$COMMIT libfabric-git 
		cd libfabric-git && sh autogen.sh;
		apt-get install -y libconfig-dev libsensors-dev libuv1-dev libfuse-dev libyaml-dev libjson-c-dev libcurl4-openssl-dev  
	    else
		wget --progress=dot:giga  https://github.com/ofiwg/libfabric/releases/download/v$OFI/libfabric-$OFI.tar.bz2 -O - | tar --no-same-owner  -xjf -
		#	    export libfabric_options=' '
	    fi 
	    cd  $ORGPWD ; echo 'pwd ' $(pwd) ;ls -lrta 
	    cd libfabric-${OFI}
	    mkdir build && cd build 
	    ../configure --prefix=$MPI_DIR $libfabric_options || { echo "OFI configuration Failure"; exit 1; }
	    make -j4 || { echo "OFI Compilation Failure"; exit 1; }
	    make install || { echo "OFI Installation Failure"; exit 1; }
	    if [ ! -f $MPI_DIR/bin/fi_info ]; then echo fi_info\ not\ found ; exit 1 ; fi 
	fi 
	cd .. 
	rm -rf libfabr* 
    fi
fi
echo ucx_or_ofi is $ucx_or_ofi
cd $ORGPWD
if [ $PMIX != "N" ]; then
    if [ ! -f /opt/mpi/lib/libpmix.so ]; then
	wget https://github.com/openpmix/openpmix/releases/download/v${PMIX}/pmix-${PMIX}.tar.gz 
	tar xzf pmix-${PMIX}.tar.gz 
	cd pmix-${PMIX} 
	./configure --prefix=${MPI_DIR} || { echo "PMIX configuration Failure"; exit 1; }
	make -j3 || { echo "PMIX Compilation Failure"; exit 1; }
	make -j3 install || { echo "PMIX installation Failure"; exit 1; }
	cd .. 
	rm -rf pmix-*.*
    fi
fi
#installing xpmem
echo 'ls -l /opt/mpi/lib/libxpmem.so' $(ls -l /opt/mpi/lib/libxpmem.so) || true
if [ ! -f /opt/mpi/lib/libxpmem.so ]; then
    wget --progress=dot:giga https://github.com/Cray-HPE/xpmem/tarball/master -O xpmem.tar.gz 
    tar xzf xpmem.tar.gz 
    rm xpmem.tar.gz 
    cd Cray-HPE-xpmem* 
    sh autogen.sh 
    ./configure --prefix=$MPI_DIR --disable-kernel-module  || { echo "XPMEM Configuration Failure"; exit 1; }
    make -j3 || { echo "XPMEM Compilation Failure"; exit 1; }
    make install || { echo "XPMEM Installation Failure"; exit 1; }
fi
cd $ORGPWD
if [ -n "${OMPI+1}" ]; then
    echo check ompi install 
    echo 'ls -l /opt/mpi/lib/libmpi.so' $(ls -l /opt/mpi/lib/libmpi.so) || true 
    if [ ! -f /opt/mpi/lib/libmpi.so ]; then
	wget  --progress=dot:giga https://download.open-mpi.org/release/open-mpi/v$ompi_major.$ompi_minor/openmpi-$OMPI.tar.gz  -O - | tar xzf -
	cd $ompi_prefix                                                       
	./configure  --prefix=${MPI_DIR} \
	$ucx_or_ofi   \
		     $ompi_options \
		     --with-xpmem=$MPI_DIR \
		     $pmix_otions \
		     --enable-mpi1-compatibility --with-slurm --without-tm --without-lsf  \
		     --without-sge --without-lustre --disable-memchecker \
		     --without-hcoll --disable-static  \
		     --disable-mpi-java --enable-dlopen --without-cuda  \
		     FC=$FC || { echo "OMPI config Failure"; exit 1; }
	head config.log 
	make FC=$FC -j 6  || { echo "OMPI Compilation Failure"; exit 1; }
	make install      || { echo "OMPI Installation Failure"; exit 1; }
	if [ ! -f $MPI_DIR/bin/mpif90 ]; then echo mpif90\ not\ found ; exit 1 ; fi 
	echo mpif90 show is $($MPI_DIR/bin/mpif90 -show) 
	cd .. ; rm -rf *tar*gz openmpi-* ucx-*
    else
	echo using cached OMPI installation
    fi
fi

if [ -n "${MPICH+1}" ]; then
    echo check mpich install 
    echo 'ls -l /opt/mpi/lib/libmpich.so' $(ls -l /opt/mpi/lib/libmpich.so) || true 
    if [ ! -f /opt/mpi/lib/libmpich.so ]; then
	$FC -v
#	if [ $MPICH = aurora ]; then
#	fi 
	if [ $mpich_major = '4' ] || [ $mpich_major = '5' ]; then
	   export mpich_options="$mpich_options $pmix_options --with-hwloc=/usr "
	else
	   export mpich_options="$mpich_options --with-hwloc-prefix=/usr "
	fi
	echo ' mpich_options is set to' $mpich_options 
	wget  --progress=dot:giga https://www.mpich.org/static/downloads/${MPICH_VERSION}/mpich-${MPICH_VERSION}.tar.gz  -O - | tar xzf -   
	cd $mpich_prefix
	if [ $mpich_major = '3' ]; then
	    wget https://raw.githubusercontent.com/pmodels/mpich/refs/tags/v4.3.2/src/pm/hydra/lib/tools/bootstrap/external/slurm_query_node_list.c 
	    mv slurm_query_node_list.c src/pm/hydra/tools/bootstrap/external/slurm_query_node_list.c
	fi 
	./configure  --prefix=$MPI_DIR   \
	$ucx_or_ofi   \
	$mpich_options \
	    --with-device=$MPICH_DEVICE  \
	    --enable-fortran=all \
	    --disable-opencl --enable-silent-rules \
	    --disable-cuda \
	    --with-xpmem=$MPI_DIR \
	    FFLAGS=' -fallow-argument-mismatch ' \
	    FCFLAGS=' -fallow-argument-mismatch ' \
	    FC=$FC || { echo "MPICH Configuration Failure"; exit 1; }
	head config.log 
	tail -300 config.log
	make FC=$FC -j 6 || { echo "MPICH Compilation Failure"; exit 1; }    
	make install|| { echo "MPICH Installation Failure"; exit 1; }
	cd .. ; rm -rf *tar*gz mpich*
    else
	echo using cached MPICH installation
    fi
fi
cd $ORGPWD

 if [ ! -f $MPI_DIR/bin/mpif90 ]; then echo mpif90\ not\ found ; exit 1 ; fi 
 echo '********'  
 export PATH=$MPI_DIR/bin:$PATH
 export LD_LIBRARY_PATH=$MPI_DIR/lib:$LD_LIBRARY_PATH

echo ' check ucx'
echo ' /opt/mpi/bin/ucx_info -v ' `/opt/mpi/bin/ucx_info -v|| true`
echo ' ucx Transports' `/opt/mpi/bin/ucx_info  -d |grep Transport |cut -c 19- || true`
echo '********'
export PATH=$MPI_DIR/bin:$PATH
export LD_LIBRARY_PATH=$MPI_DIR/lib:$LD_LIBRARY_PATH
export PATH=$PATH:/usr/local/cuda-"$CUDA_VERSION_MAJOR"."$CUDA_VERSION_MINOR"/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-"$CUDA_VERSION_MAJOR"."$CUDA_VERSION_MINOR"/lib64
export PATH=$PATH:"$ROCM_PATH"/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"$ROCM_PATH"/lib
if [ $(command -v mpicc) ]; then echo mpicc present; else echo mpicc missing; exit 1; fi 
echo "which mpicc is" $(which mpicc) 
echo "mpicc -show is " $(mpicc -show)  || { tail -700 $ompi_prefix/config.log ;echo "mpi compilation failed"; exit 1; }
echo GA_RUNTIME is $GA_RUNTIME 
echo EXACHEM_BRANCH is ${EXACHEM_BRANCH}  
echo TAMM_BRANCH is ${TAMM_BRANCH}  
echo 'cloning tamm source *** ' || true  
cd /opt || { echo "Failure"; exit 1; } 
git clone -b ${EXACHEM_BRANCH} --depth 100  https://github.com/ExaChem/exachem.git exachem   
git clone -b ${TAMM_BRANCH} --depth 100 https://github.com/NWChemEx/TAMM.git  
cd TAMM  
export NO_STOP_MESSAGE=1
mkdir build && cd build 
CMAKE_OPTIONS="-DCMAKE_INSTALL_PREFIX=/opt/install/exachem -DMODULES='CC' " 
CMAKE_OPTIONS="$CMAKE_OPTIONS -DBLAS_ARCH=zen3 -DMARCH_FLAGS=-march=znver3" 
if [ ${GPU} = "nvidia" ]; then echo "nvidia gpu "; CMAKE_OPTIONS="$CMAKE_OPTIONS -DTAMM_ENABLE_CUDA=ON -DGPU_ARCH=${GPU_ARCH}" ; fi 
if [ ${GPU} = "amd" ]; then echo "amd gpu "; CMAKE_OPTIONS="$CMAKE_OPTIONS -DTAMM_ENABLE_HIP=ON -DROCM_ROOT=$ROCM_PATH -DGPU_ARCH=${GPU_ARCH} -DGCCROOT=/usr " ; ls -lrt $ROCM_PATH/include/rocblas/rocblas.h $ROCM_PATH/include/ ; ln -sf $ROCM_PATH/include/rocblas/rocblas.h $ROCM_PATH/include/rocblas.h; fi  
if [ ${ELPA} = "Y" ]; then echo "ELPA enabled "; CMAKE_OPTIONS="$CMAKE_OPTIONS -DTAMM_ENABLE_ELPA=ON" ; fi  
CMAKE_OPTIONS="$CMAKE_OPTIONS -DGA_RUNTIME=${GA_RUNTIME}"
export CMAKE_OPTIONS
echo CMAKE_OPTIONS $CMAKE_OPTIONS 
CC="$CC" CXX="$CXX" FC="$FC" cmake  $CMAKE_OPTIONS .. || { echo "Cmake failure"; exit 1; } 
make -j3 || { echo "TAMM Compilation failure"; 
	    cat /opt/TAMM/build/TAMM_External-prefix/src/TAMM_External-build/GlobalArrays_External-prefix/src/GlobalArrays_External-build/CMakeFiles/CMakeOutput.log || true ; 
            cat /opt/TAMM/build/TAMM_External-prefix/src/TAMM_External-build/GlobalArrays_External-prefix/src/GlobalArrays_External-build/CMakeFiles/CMakeError.log || true; exit 1; } 
echo exit code for TAMM compilation $?  
make install  
echo exit code for TAMM make install $?  
cd /opt/exachem  
mkdir build && cd build  
echo ' === ls -l /opt/install/exachem ===' $(ls -l /opt/install/exachem)  
echo ' === ls -l /opt/install/exachem/lib ===' $(ls -l /opt/install/exachem/lib)  
if [ -f /opt/install/exachem/lib/libint2.a ]
then
    echo 'found libint cache'
    mkdir -p /opt/exachem/build/stage/opt || true 
    rsync -av /opt/install /opt/exachem/build/stage/opt/.
fi 
export CMAKE_OPTIONS 
echo CMAKE_OPTIONS $CMAKE_OPTIONS 
CC="$CC" CXX="$CXX" FC="$FC" cmake  $CMAKE_OPTIONS .. || { echo "Cmake failure"; exit 1; } 
make V=1 VERBOSE=1 -j2 -l1.5 || { echo "Exachem Compilation failure"; exit 1; } 
echo exit code for compilation $? 
make install 
echo exit code for make install $? 
bash -c "if [[ -f /opt/install/exachem/bin/ExaChem ]]; then echo 'Exachem binary created' ; else  echo 'compilation error1'; exit 1; fi"  
echo git describe --always `git describe --always`  >> /opt/install/info.txt
echo git rev-parse HEAD git `git rev-parse HEAD` >> /opt/install/info.txt
echo 'clean unnecessary source to reduce docker size'
rm  -rf /opt/exachem
rm  -rf /opt/*patch
rm  -rf /opt/TAMM
echo 'clean unnecessary packages '
DEBIAN_FRONTEND=noninteractive apt-get -q=2 -y install localepurge
echo MANDELETE >  /etc/locale.nopurge
echo DONTBOTHERNEWLOCALE >> /etc/locale.nopurge
echo en_US.UTF-8 >> /etc/locale.nopurge
localepurge
rm -rf /usr/share/doc
apt-get -q=2 -y purge   patch curl  wget  make git cpp-"$GCC_VERSION" gfortran-"$GCC_VERSION" gcc-"$GCC_VERSION" libicu-dev libpython"$PY_VERSION"-dev libstdc++-"$GCC_VERSION"-dev libc6-dev libgcc-"$GCC_VERSION"-dev libgfortran-"$GCC_VERSION"-dev  || true
apt-get -q=2 -y install libgfortran5 libgomp1 && apt-get clean
if [ "$GPU" = nvidia ]
then
    apt-get purge -y cuda-cccl-"$CUDA_VERSION_MAJOR"-"$CUDA_VERSION_MINOR" libcublas-dev-"$CUDA_VERSION_MAJOR"-"$CUDA_VERSION_MINOR"
fi
if [ "$GPU" = "amd" ]
then
    apt-get  purge -y  cmake git-man openmp-extras \
     lib32gcc-11-dev  libc6-dev-i386 libx32gcc-11-dev libc6-dev-x32 lib32gcc-11-dev  \
     lib32asan6 lib32atomic1 lib32gcc-s1 lib32gomp1 lib32itm1 lib32quadmath0 lib32stdc++6 lib32ubsan1 libc6-i386 \
     libc6-x32 libx32asan6 libx32atomic1 libx32gcc-s1 libx32gomp1 libx32itm1 libx32quadmath0 libx32stdc++6 libx32ubsan1 \
     javascript-common less liberror-perl libjs-jquery libjs-sphinxdoc libjs-underscore libltdl-dev libltdl7 libpython3.10 linux-headers-generic
    apt-get install -y hip-runtime-amd rocblas openmp-extras-runtime
    cd $ROCM_PATH/lib/rocblas/ ; mkdir keep ; mv library/*"$GPU_ARCH"* keep/.  
    rm -rf library ; mv keep library 
    rm -rf "$ROCM_PATH"/bin  "$ROCM_PATH"/llvm/bin  
    mkdir -p "$ROCM_PATH"/bin  && ln -sf "$ROCM_PATH"/libexec/rocm_smi/rocm_smi.py "$ROCM_PATH"/bin/rocm-smi
fi
echo '*** ls -l CC/bin **'
ls -l /opt/install/exachem/bin/ || true
echo '*** ldd ***' 
LD_LIBRARY_PATH=/usr/local/lib:/opt/lib ldd /opt/install/exachem/bin/ExaChem || true
DEBIAN_FRONTEND=noninteractive apt-get clean -y
DEBIAN_FRONTEND=noninteractive apt-get -y install localepurge
echo MANDELETE >  /etc/locale.nopurge
echo DONTBOTHERNEWLOCALE >> /etc/locale.nopurge
echo en_US.UTF-8 >> /etc/locale.nopurge
localepurge
rm -rf /usr/share/doc  /usr/share/man
du -sk /opt/*|sort -n
echo "dddddddddddd" 
dpkg-query -Wf '${Installed-Sizet${Package}\n' | sort -n | tail -n 50 \
echo "dddddddddddd"
 du -sk /tmp/* || true
 ls -lart /tmp ||true
ls -Rlart  /opt/install/exachem || true
ls -lart  /opt/install/exachem/include || true
ls -lart  /opt/install/exachem || true 

#&&  apt-get  -y purge cmake git  gcc-11  g++-11  gfortran-11  libstdc++-11-dev  libgcc-11-dev git
#&& apt-get -y install libgcc-s1 libgfortran5 \
#&& apt-get -y autoremove && apt-get clean




#cd /data
%environment
export MPI_DIR=/opt/mpi
export SINGULARITY_MPI_DIR=$MPI_DIR
export CUDA_VERSION_MAJOR=11 
export CUDA_VERSION_MINOR=7
export PATH=/opt/install/exachem/bin:$MPI_DIR/bin:/usr/local/cuda-"$CUDA_VERSION_MAJOR"."$CUDA_VERSION_MINOR"/bin:"$ROCM_PATH"/bin/:$PATH
export LD_LIBRARY_PATH=$MPI_DIR/lib:/usr/local/cuda-"$CUDA_VERSION_MAJOR"."$CUDA_VERSION_MINOR"/lib64:/usr/local/lib:$MPI_DIR/lib:"$ROCM_PATH"/lib:$LD_LIBRARY_PATH:
export SINGULARITYENV_APPEND_PATH=/opt/install/exachem/bin:$MPI_DIR/bin:/usr/local/cuda-"$CUDA_VERSION_MAJOR"."$CUDA_VERSION_MINOR"/bin:"$ROCM_PATH"/bin
export SINGULARITYENV_APPEND_LD_LIBRARY_PATH=$MPI_DIR/lib:/usr/local/cuda-"$CUDA_VERSION_MAJOR"."$CUDA_VERSION_MINOR"/lib64:/usr/local/lib:$MPI_DIR/lib:$ROCM_PATH/lib
export COMEX_MAX_NB_OUTSTANDING=12
export SINGULARITY_COMEX_MAX_NB_OUTSTANDING=12
#%runscript
#exec /bin/bash "$@"

