name: exachem_apptainer_merge

on:
  push:
    paths-ignore:
      - apptainer.ompi41x
      - apptainer.ompi5x
      - apptainer.mpich
      - shifter.nersc
  schedule:
    - cron: '0 0 * * SUN'
  pull_request:
  repository_dispatch:
    types: [backend_automation]
  workflow_dispatch:

jobs:
  build_source_caches:
    uses: ./.github/workflows/create_source_caches.yaml
  build_image:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    strategy:
        fail-fast: false
        matrix:
          folder:
            - apptainer.merge
          exachem_branch:
            - main
          cc:
            - gcc
          tamm_branch:
            - main
          mpi_impl:
            - mpich
          mpich:
            - 3.4.2
          mpich_device:
            - ch4:ofi
          ofi:
            - builtin
          ucx:
            - N
          ga_runtime:
            - MPI_PROGRESS_RANK
          gpu:
            - cpu
            - amd_gfx90a_rocm7.0.2
            - amd_gfx90a_rocm6.4.4
            - nvidia_70
            - nvidia_80
          ubuntu:
            - noble
          scalapack:
            - y
          elpa:
            - n
          include:
            - ompi: 4.1.8
              mpi_impl: ompi
              mpich_device: ch4:ofi
              ofi: N
              ucx: 1.14.1
              cc: gcc
              ga_runtime: MPI_PROGRESS_RANK
              ubuntu: noble
              gpu: cpu
              exachem_branch: main
              tamm_branch: main
              folder: apptainer.merge
              scalapack: y
              elpa: y
            - ompi: 5.0.10
              mpi_impl: ompi
              mpich_device: ch4:ofi
              ofi: N
              ucx: 1.15.0
              cc: gcc
              ga_runtime: MPI_PROGRESS_RANK
              ubuntu: noble
              gpu: cpu
              exachem_branch: main
              tamm_branch: main
              folder: apptainer.merge
              scalapack: y
              elpa: y
            - ompi: 4.1.8
              mpi_impl: ompi
              mpich_device: ch4:ofi
              ofi: N
              ucx: 1.14.1
              cc: gcc
              ga_runtime: MPI_PROGRESS_RANK
              ubuntu: noble
              gpu: amd_gfx90a_rocm7.2.4
              exachem_branch: main
              tamm_branch: main
              folder: apptainer.merge
              scalapack: y
              elpa: y
            - ompi: 4.1.8
              mpi_impl: ompi
              mpich_device: ch4:ofi
              ofi: N
              ucx: 1.14.1
              cc: gcc
              ga_runtime: MPI_PROGRESS_RANK
              ubuntu: noble
              gpu: nvidia_70
              exachem_branch: main
              tamm_branch: main
              folder: apptainer.merge
              scalapack: y
              elpa: y
            - mpich: 4.2.3
              mpi_impl: mpich
              mpich_device: ch4:ofi
              ofi: builtin
              ucx: N
              cc: gcc
              ga_runtime: MPI_PROGRESS_RANK
              ubuntu: noble
              gpu: cpu
              exachem_branch: main
              tamm_branch: main
              folder: apptainer.merge
              scalapack: y
              elpa: y
            - mpich: 4.2.3
              mpi_impl: mpich
              mpich_device: ch4:ucx
              ofi: N
              ucx: 1.15.0
              cc: gcc
              ga_runtime: MPI_PROGRESS_RANK
              ubuntu: noble
              gpu: cpu
              exachem_branch: main
              tamm_branch: main
              folder: apptainer.merge
              scalapack: y
              elpa: y
            - ompi: 5.0.10
              mpi_impl: ompi
              mpich_device: ch4:ucx
              ofi: N
              ucx: 1.15.0
              cc: gcc
              ga_runtime: MPI_PROGRESS_RANK
              ubuntu: noble
              gpu: nvidia_80
              exachem_branch: main
              tamm_branch: main
              folder: apptainer.merge
              scalapack: y
              elpa: y
            - ompi: 5.0.10
              mpi_impl: ompi
              mpich_device: ch4:ucx
              ofi: N
              ucx: 1.17.0
              cc: gcc
              ga_runtime: MPI_PROGRESS_RANK
              ubuntu: noble
              gpu: nvidia_80
              exachem_branch: main
              tamm_branch: main
              folder: apptainer.merge
              scalapack: y
              elpa: y
            - mpich: 4.2.3
              mpi_impl: mpich
              mpich_device: ch4:ofi
              ofi: builtin
              ucx: N
              cc: gcc
              ga_runtime: MPI_PROGRESS_RANK
              ubuntu: noble
              gpu: nvidia_70
              exachem_branch: main
              tamm_branch: main
              folder: apptainer.merge
              scalapack: y
              elpa: y
            - mpich: 4.2.3
              mpi_impl: mpich
              mpich_device: ch4:ofi
              ofi: builtin
              ucx: N
              cc: gcc
              ga_runtime: MPI_PROGRESS_RANK
              ubuntu: noble
              gpu: nvidia_80
              exachem_branch: main
              tamm_branch: main
              folder: apptainer.merge
              scalapack: y
              elpa: y
    steps:
    - name: Get Instruction
      id: get-simd
      run: |
        /usr/bin/lscpu
        curl -LJO https://raw.githubusercontent.com/nwchemgit/nwchem/master/travis/guess_simd.sh
        chmod +x guess_simd.sh
        curl -LJO https://raw.githubusercontent.com/nwchemgit/nwchem/master/travis/cpuinfo.sh
        chmod +x cpuinfo.sh
        ./cpuinfo.sh
        echo "simd=$(./guess_simd.sh)" >> $GITHUB_ENV
        echo "microarch=$(cat /tmp/microarch_$(id -u).txt)" >> $GITHUB_ENV
    - name: exachem version tag
      run: |
        if [[ ${{ matrix.exachem_branch }} != main ]]; then
           myversion=.${{ matrix.exachem_branch }}
        fi
        myversion+=.${{ matrix.gpu }}
        if [[ ${{ matrix.cc }} !=  gcc ]]; then
          myversion+=.${{ matrix.cc }}
        fi
        if [[ ${{ matrix.ga_runtime }} !=  MPI_PROGRESS_RANK ]]; then
          net_tag=$(echo ${{ matrix.ga_runtime }} | tr '[:upper:]' '[:lower:]')
          myversion+=.${net_tag}
        fi
        if [[ ${{ matrix.ubuntu }} !=  focal ]]; then
          myversion+=.${{ matrix.ubuntu }}
        fi
        if [[ ${{ matrix.mpich_device }} !=  ch4:ofi ]]; then
          dev_tag=$(echo ${{ matrix.mpich_device }} | sed  's/:/_/' )
          echo "mpich_device="${dev_tag} >> $GITHUB_ENV
        fi
        if [[ ${{ matrix.ofi }} !=  N ]]; then
           if [[ ${{ matrix.ofi }} !=  builtin ]]; then
               myversion+=.libfabric-${{ matrix.ofi }}
           fi
        fi
        if [[ ${{ matrix.ucx }} !=  N ]]; then
               myversion+=.ucx-${{ matrix.ucx }}
        fi
        echo "exachemversion=$myversion" >> $GITHUB_ENV
    - name: tag0
      run: |
        echo "tag0=${{ matrix.mpi_impl }}${{ matrix.ompi }}${{ matrix.mpich }}${{ env.mpich_device }}" >> $GITHUB_ENV
    - name: cache tag
      run: |
        echo "cache_tag=${{ env.tag0 }}${{ env.simd }}${{ env.microarch}}${{ env.exachemversion}}" >> $GITHUB_ENV
    - name: gh actions tag
      run: |
        echo "tag=$(echo oras://ghcr.io/${{ github.repository }}/apptainer.merge${{ env.tag0 }}${{ env.exachemversion}} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
    - name: echo-tag
      run: |
        echo " the apptainer tag is  ${{ env.tag }}"
        echo " the cache tag is ${{ env.cache_tag }}"
    - name: Checkout image source
      uses: actions/checkout@v7
      with:
        clean: false
    - name: pkg cleanup
      uses: edoapra/ubuntu-pkg-cleanup@main
    - name: Setup libint source cache
      id: setup-libinttar-cache
      uses: actions/cache@v6
      with:
        path: |
          ~/cache_libint
        key: libint_2131
    - name: check source caches
      run: |
        ls -lart ~/cache_libint || true
        if [[ -f ~/cache_libint/libint-2.13.1.tar.xz ]]; then echo  "libint source tar cache present"
        else
          echo "libint source tar not found"
        fi
        if [[ -f ~/cache_libint/elpa-2026.02.002.tar.gz ]]; then echo  "elpa source tar cache present"
        else
          echo "elpa source tar not found"
        fi
        if [[ -f ~/cache_libint/eigen_master.tar.gz ]]; then echo  "eigen source tar cache present"
        else
          echo "eigen source tar not found"
        fi
    - name: Setup cache
      id: setup-cache
      uses: actions/cache@v6
      with:
        path: |
          ~/cache
        key: "${{ env.cache_tag }}"
    - name: fetch cache
      if: steps.setup-cache.outputs.cache-hit == 'true'
      run: |
        ls -lart ~/cache
        if [[ -f ~/cache/mpi/lib/libmpi.a ]]; then \
        echo "mpich cache present" ; \
        fi
        if [[ -f ~/pmix/etc/pmix-mca-params.conf ]]; then
        echo "pmix cache present" ; \
        fi
        if [[ -f ~/cache/libint.tar.bz2 ]]; then \
        echo "libint cache present" ; \
        fi
        if [[ -f ~/cache/libxc.tar.bz2 ]]; then \
        echo "libxc cache present" ; \
        fi
        if [[ -f ~/cache/libelpa.tar.bz2 ]]; then \
        echo "libelpa cache present" ; \
        fi
    - name: Install apptainer
      env:
        APP_VER: 1.4.5
      run: |
        sudo apt-get install -y  libfuse2 libseccomp2 zlib1g uidmap squashfs-tools squashfuse fuse2fs fuse-overlayfs fakeroot
        wget -q  https://github.com/apptainer/apptainer/releases/download/v${APP_VER}/apptainer_${APP_VER}_amd64.deb  -O apptainer.deb
        wget -q  https://github.com/apptainer/apptainer/releases/download/v${APP_VER}/apptainer-suid_${APP_VER}_amd64.deb  -O apptainers.deb
        sudo dpkg -i apptainer*.deb
        which apptainer
        apptainer version
    - name: create sif from docker
      run: |
        if [  -f ~/cache/ubuntu_${{ matrix.ubuntu }}.sif ]; then echo "sif found" ; \
           cp ~/cache/ubuntu_${{ matrix.ubuntu }}.sif ${{ matrix.folder }}/.
        else
           cd ${{ matrix.folder }} ;\
        apptainer pull docker://ubuntu:${{ matrix.ubuntu }} ; \
        fi
    - name: copy patch
      run: |
        pwd
        ls -lrta
        cp patches/myaug.patch ${{ matrix.folder }}
        ls -lrta ${{ matrix.folder }}
    - name: push_false
      id: push_false
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        echo "push_truefalse=false" >> $GITHUB_ENV
    - name: push_true
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        echo "push_truefalse=true" >> $GITHUB_ENV
    - name: build an apptainer container
      run: |
        cd ${{ matrix.folder }}
        sudo mkdir /mnt/tmpdir
        sudo chmod -R uog+rwx /mnt/tmpdir
        echo 'this is a test' > /mnt/tmpdir/test.txt
        if [[ $(echo ${{ matrix.gpu }} | cut -c 1-3)  == 'amd' ]]; then  export ROCM_OPT=" --rocm ";fi
        SCALAPACK=${{ matrix.scalapack }} ELPA=${{ matrix.elpa }} UCX=${{ matrix.ucx }} OFI=${{ matrix.ofi }} MPICH_DEVICE=${{ matrix.mpich_device }} MPICH=${{ matrix.mpich }} MYUSERNAME=${{ github.actor}}  EXACHEM_BRANCH=${{ matrix.exachem_branch}} TAMM_BRANCH=${{ matrix.tamm_branch}} GPU=${{ matrix.gpu}} CC=${{ matrix.cc }} GA_RUNTIME=${{ matrix.ga_runtime}}  MPI_IMPL=${{ matrix.mpi_impl }} MPICH=${{ matrix.mpich}} OMPI=${{ matrix.ompi }} apptainer build --build-arg UBUNTU_VERSION=${{ matrix.ubuntu}} $ROCM_OPT --fakeroot  /mnt/tmpdir/exachem.simg  Singularity
    - name: Check compilation result
      if: ${{ failure() }}
      run: |
        grep -A 30 cublasLtHeuristicsCacheSetCapacity $(find /opt/TAMM/build -name ELPA_External)/config.log
    - name: builddate
      id: build-date
      run: |
        echo "date=$(TZ=America/Los_Angeles date +%Y%m%d_%H%M%S)" >> $GITHUB_ENV
    - name: push to ghcr.io
      if: ${{ env.push_truefalse == 'true' }}
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | apptainer registry login -u ${{ github.actor }} --password-stdin oras://ghcr.io
        apptainer remote list
        exit_code=0
        tries=0 ; until [ "$tries" -ge 5 ] ; do \
        apptainer push /mnt/tmpdir/exachem.simg ${{ env.tag }}:${{ env.date }} \
        && break ;\
        tries=$((tries+1)) ; echo " first push no.1 attempt no. $tries" ; sleep 30 ; done
        tries=0 ; until [ "$tries" -ge 5 ] ; do \
        apptainer push /mnt/tmpdir/exachem.simg ${{ env.tag }}:latest \
        && break ;\
        tries=$((tries+1)) ; echo " second push  attempt no. $tries" ; sleep 30 ; done
    - name: store cache
      if: ${{ (steps.setup-cache.outputs.cache-hit != 'true') && (env.push_truefalse == 'true') }}
      run: |
        cd ${{ matrix.folder }}
        ../utils/create_cache.sh /mnt/tmpdir/exachem.simg
        cp ubuntu_${{ matrix.ubuntu }}.sif ~/cache/.
        #cp /opt/libint-2.13.1.tar.xz ~/cache_libint
        echo "cache stored"
        ls -l ~/cache
        ls -l ~/cache_libint
    - name: ldd check
      if: ${{ env.push_truefalse == 'true' }}
      run: |
        pwd
        ls -la
        export APPTAINER_DISABLE_CACHE=True
        attempts=0
        max_attempts=3
        until  apptainer pull -F ${{ env.tag }}:${{ env.date }}  > /dev/null ; do
            if [  "$attempts" -gt $max_attempts ]; then
                echo "pull failed after $max_attempts attempts"
                exit 1
            else
                echo "pull failed. sleeping for 5s"
                sleep 5s
                attempts+=1
            fi
        done
        sudo apt-get install -y openmpi-bin libmpich-dev mpich
        mpirun --version || true
        ldd `which mpirun`
        apptainer exec ${{ env.tag }}:latest ldd /opt/install/exachem/bin/ExaChem
    - name: test cpu image with apptainer
      if: ${{ (env.push_truefalse == 'true') && (matrix.gpu == 'cpu') }}
      run: |
        pwd
        ls -la
        export APPTAINER_DISABLE_CACHE=True
        attempts=0
        max_attempts=3
        until  apptainer pull -F ${{ env.tag }}:${{ env.date }}  > /dev/null ; do
            if [  "$attempts" -gt $max_attempts ]; then
                echo "pull failed after $max_attempts attempts"
                exit 1
            else
                echo "pull failed. sleeping for 5s"
                sleep 5s
                attempts+=1
            fi
        done
        export UCX_TLS=tcp,self
        export UCX_POSIX_USE_PROC_LINK=n
        export OMPI_MCA_osc=^ucx
        export OMPI_MCA_btl_vader_single_copy_mechanism=none
        export OMPI_MCA_smsc=^knem
        export PMIX_MCA_gds=^shmem
        export PMIX_MCA_psec=^munge
        export PATH=/opt/mpi/bin:$PATH
        export LD_LIBRARY_PATH=/opt/mpi/lib:$LD_LIBRARY_PATH
        export MPI_IMPL=${{ matrix.mpi_impl }}
        echo MPI_IMPL is $MPI_IMPL
        if [[ $MPI_IMPL == aurora ]] || [[ $MPI_IMPL == ompi ]] ; then
           sudo apt-get install -y openmpi-bin openmpi-common libopenmpi-dev
           export MPIRUN_PATH=`which mpirun.openmpi`
        fi
        if [[ $MPI_IMPL == mpich ]]; then
           sudo apt-get install -y libmpich-dev mpich
           export MPIRUN_PATH=`which mpirun.mpich`
        fi
        echo "MPIRUN_PATH is" $MPIRUN_PATH
        $MPIRUN_PATH --version || true
        export ASAN_OPTIONS=allocator_may_return_null=1 
        timeout 5m $MPIRUN_PATH -np 2 apptainer exec ${{ env.tag }}:${{ env.date }} \
        /opt/install/exachem/bin/ExaChem \
        inputs/waterdft.json
        echo exit code is $?
