name: Clear all Github Actions caches
on:
  schedule:
    - cron: "0 23 28 * *"
  repository_dispatch:
    types: [backend_automation]
  workflow_dispatch:

jobs:
  my-job:
    name: Delete all caches
    runs-on: ubuntu-latest

    steps:
      - name: Clear all caches
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          #gh cache delete --all --repo ${{ github.repository }}
          ids=$(gh cache list -R ${{ github.repository }} --limit 100 --json id,key | jq -r --arg pattern "libint" '.[] | select(.key | test($pattern) | not) | .id')
          if [ -n "$ids" ]; then
            echo "deleting cache $ids"
            echo "$ids" | xargs -I {} gh cache delete {} -R ${{ github.repository }}
          else
            echo "No matching caches found to delete."
          fi
